name: 'Angular coverage badges'
description: 'GitHub action that generates coverage badges for Angular projects without external providers and updates a GitHub repository automatically'
author: 'Taras Demyanets'
inputs:
  coverage-summary-path:
    description: 'Path to a "coverage-summary.json" file. Defaults to "./coverage/coverage-summary.json"'
    default: './coverage/coverage-summary.json'
    required: false
  badges-directory:
    description: 'Writes the coverage badges to the given directory. Defaults to "./badges" for root "src" project or "./badges/<library> for a library'
    default: ''
    required: false
  protected-branches:
    description: 'List of protected branches that require review for commit. Defaults to empty list ([])'
    default: '[]'
    required: false
  write-debug-logs:
    description: 'Writes extra debug logs to console if set to "true"'
    default: ''
    required: false
branding:
  color: 'red'
  icon: 'shield'
runs:
  using: 'node12'
  main: 'dist/index.js'
