name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        coverage-summary-path: __test__/assets/coverage-summary.json
        badges-directory: __test__/temp
        protected-branches: '["master", "develop"]'